### ISSUE TITLE
Create a nuget package

### ISSUE THREAD

**Issue by kjeremy** [alexsorokoletov/Xamarin.Android.Maps.Utils#1]
Can you create a nuget package for this?

**Comment by Confusingboat** [comment]
+1

**Comment by alexsorokoletov** [comment]
Hi everyone!
Package has been published :) https://www.nuget.org/packages/Xamarin.Android.Maps.Utils
I am not sure how do we version it, since google maps utils now has it's own versions (currently it's 0.4.4) 

Any suggestions on that?

**Comment by alexsorokoletov** [comment]
Closing the issue with #3
