### ISSUE TITLE
The library cause NUllPointerException

### ISSUE THREAD

**Issue by lfongaroScp** [alexsorokoletov/Xamarin.Android.Maps.Utils#4]
Hi,

Today (12 th January 2017) I try to use your binding. I just install it via nuget but at the launch my app crash with this exception:
"Java.Lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.ContentFrameLayout.setId(int)' on a null object reference"

If I remove the package the app runs normally. It is strange, but I try many times.

Step to reproduce:
Install the nuget package in a App that use also "Xamarin.Android.Support.v7.AppCompat" and launch the app.

**Comment by alexsorokoletov** [comment]
@lfongaroScp interesting, can you provide me with a sample app that reproduces the problem? I will be able to look

**Comment by alexsorokoletov** [comment]
@lfongaroScp I will be closing this issue soon if no feedback provided.

**Comment by lfongaroScp** [comment]
Hi,

Sorry I forgot to update this thread. After the last release of the android.support.v7 by Xamarin this problem seems disappear and the library work with no problem.

regards,
