### ISSUE TITLE
Update to 0.5.5

### ISSUE THREAD

**Issue by andreabonassi** [alexsorokoletov/Xamarin.Android.Maps.Utils#5]
Is in program an update to 0.5.5 version?

**Comment by alexsorokoletov** [comment]
@andreabonassi latest version seems to be 0.5.1-snapshot
https://github.com/googlemaps/android-maps-utils/blob/master/gradle.properties

What exactly are you looking for in the updated version?

**Comment by andreabonassi** [comment]
I developed an application that shows on the map up to 5000 points. I Use
the cluster and seems very slow when I make zoom and unzoom.

is there a way to make my application more powerful?



Thanks.



*Da:* Alex Sorokoletov [mailto:notifications@github.com]
*Inviato:* venerdì 10 marzo 2017 00:27
*A:* alexsorokoletov/Xamarin.Android.Maps.Utils
*Cc:* andreabonassi; Mention
*Oggetto:* Re: [alexsorokoletov/Xamarin.Android.Maps.Utils] Update to 0.5.5
(#5)



@andreabonassi <https://github.com/andreabonassi> latest version seems to
be 0.5.1-snapshot
https://github.com/googlemaps/android-maps-utils/blob/master/gradle.properties

What exactly are you looking for in the updated version?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/alexsorokoletov/Xamarin.Android.Maps.Utils/issues/5#issuecomment-285517649>,
or mute the thread

**Comment by alexsorokoletov** [comment]
@andreabonassi I suggest you publish a sample app exhibiting problem and then go from there. Check StackOverflow or try to reproduce 5k of markers in Java Android app and see if it's something wrong with library, Xamarin or something else.

Usually problem might be with loading images for markers. i.e. if you are loading image for each marker every time that might hit performance a lot. Load it once.
If you are using custom view for markers, rendering this custom view to bitmap (that what GoogleMaps for Android does) might be another performance hit. In that case you want to make your marker view as simple as possible.

**Comment by andreabonassi** [comment]
I don’t use custom marker or cluster, but it seems that face struggle to
load a large number of points.

You planning to upgrade nuget to xamarin?



Thanks.



*Da:* Alex Sorokoletov [mailto:notifications@github.com]
*Inviato:* sabato 11 marzo 2017 04:55
*A:* alexsorokoletov/Xamarin.Android.Maps.Utils
*Cc:* andreabonassi; Mention
*Oggetto:* Re: [alexsorokoletov/Xamarin.Android.Maps.Utils] Update to 0.5.5
(#5)



@andreabonassi <https://github.com/andreabonassi> I suggest you publish a
sample app exhibiting problem and then go from there. Check StackOverflow
or try to reproduce 5k of markers in Java Android app and see if it's
something wrong with library, Xamarin or something else.

Usually problem might be with loading images for markers. i.e. if you are
loading image for each marker every time that might hit performance a lot.
Load it once.
If you are using custom view for markers, rendering this custom view to
bitmap (that what GoogleMaps for Android does) might be another performance
hit. In that case you want to make your marker view as simple as possible.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/alexsorokoletov/Xamarin.Android.Maps.Utils/issues/5#issuecomment-285839706>,
or mute the thread

**Comment by alexsorokoletov** [comment]
Updated. Feel free to choose any version you like :)

**Comment by andreabonassi** [comment]
Thanks.



*Da:* Alex Sorokoletov [mailto:notifications@github.com]
*Inviato:* sabato 25 marzo 2017 09:15
*A:* alexsorokoletov/Xamarin.Android.Maps.Utils
*Cc:* andreabonassi; Mention
*Oggetto:* Re: [alexsorokoletov/Xamarin.Android.Maps.Utils] Update to 0.5.5
(#5)



Closed #5
<https://github.com/alexsorokoletov/Xamarin.Android.Maps.Utils/issues/5>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/alexsorokoletov/Xamarin.Android.Maps.Utils/issues/5#event-1015281680>,
or mute the thread
