### ISSUE TITLE
Not work from latest version of Xamarin.GooglePlayServices.Maps

### ISSUE THREAD

**Issue by ghost** [alexsorokoletov/Xamarin.Android.Maps.Utils#6]
Hi,

I update the component Xamarin.GooglePlayServices.Maps (and his dependecies as well), now the library crash when call the method Android.Gms.Common.Zze.IsGooglePlayServicesAvailable (It seems removed from the native component).

Can you check this problem?

Regards,

**Comment by alexsorokoletov** [comment]
@lfongaroScp hey, thanks for the report.
Do you have a crash callstack?

**Comment by ghost** [comment]
It's not a great log, but here it is:

> 06-07 09:32:23.355 I/MonoDroid(29339): UNHANDLED EXCEPTION:
> 06-07 09:32:23.392 I/MonoDroid(29339): System.MissingMethodException: Method 'Android.Gms.Common.Zze.IsGooglePlayServicesAvailable' not found.
> 06-07 09:32:23.392 I/MonoDroid(29339):   at Android.Support.V4.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_inflater, System.IntPtr native_container, System.IntPtr native_savedInstanceState) [0x00022] in <7e083afc7c9045f59e01d9c14931060d>:0 
> 06-07 09:32:23.392 I/MonoDroid(29339):   at (wrapper dynamic-method) System.Object:2574f41a-2aa2-4938-8e42-3c6354483b02 (intptr,intptr,intptr,intptr,intptr)
> 06-07 09:32:23.410 W/art     (29339): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
> 06-07 09:32:23.415 D/Mono    (29339): DllImport searching in: '__Internal' ('(null)').
> 06-07 09:32:23.415 D/Mono    (29339): Searching for 'java_interop_jnienv_throw'.
> 06-07 09:32:23.415 D/Mono    (29339): Probing 'java_interop_jnienv_throw'.
> 06-07 09:32:23.415 D/Mono    (29339): Found as 'java_interop_jnienv_throw'.
> 06-07 09:32:23.894 E/mono    (29339): 
> 06-07 09:32:23.894 E/mono    (29339): Unhandled Exception:
> 06-07 09:32:23.894 E/mono    (29339): System.MissingMethodException: Method 'Android.Gms.Common.Zze.IsGooglePlayServicesAvailable' not found.
> 06-07 09:32:23.895 E/mono-rt (29339): [ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: Method 'Android.Gms.Common.Zze.IsGooglePlayServicesAvailable' not found.

I check twice, my app do not call that method, but instead I use
GoogleApiAvailability.Instance.IsGooglePlayServicesAvailable(Activity);
However it crash before my Fragment enter in the OnCreateView method.

**Comment by ghost** [comment]
I can confirm the problem is the native component. I download the java code, update the dependencies (the java project use an old version of google maps), get the aar file, adjust your project binding metadata.xml and compile. Then I use the new dll and the app not crash. However I'm not 100% sure about my work, so I wait your release trough nuget.

**Comment by alexsorokoletov** [comment]
@lfongaroScp thank you for the info.
If you can share sample app that crashes with this component it would be great.
I'll try to fix the component asap.

**Comment by lfongaroScp** [comment]
Hi,
After another update of Xamarin.GooglePlayServices.Maps (version 42.1021.1) the crash do not occur anymore.
In fact it wasn't only a bug of the Xamarin.GooglePlayServices.Maps version 42.1001.0, the problem is also the use of an old library (version 9.x the last stable version is 11.x) in the native component and a bad reference: Google suggest to target only the single component and not the entire google.play library
https://developers.google.com/android/guides/setup#split . 

I will open an issue in the native project, I hope they update their reference.

Thanks for the time you give me. I close this issue.
Regards,

P.S. I attach a sample project that crash, so you can get more info if you need it.
[MapUtilsCrash.zip](https://github.com/alexsorokoletov/Xamarin.Android.Maps.Utils/files/1090797/MapUtilsCrash.zip)

**Comment by ghost** [comment]
Hi,
After another update of Xamarin.GooglePlayServices.Maps (version 42.1021.1) the crash do not occur anymore.
In fact it wasn't only a bug of the Xamarin.GooglePlayServices.Maps version 42.1001.0, the problem is also the use of an old library (version 9.x the last stable version is 11.x) in the native component and a bad reference: Google suggest to target only the single component and not the entire google.play library
https://developers.google.com/android/guides/setup#split . 

I will open an issue in the native project, I hope they update their reference.

Thanks for the time you give me. I close this issue.
Regards,

P.S. I attach a sample project that crash, so you can get more info if you need it.
[MapUtilsCrash.zip](https://github.com/alexsorokoletov/Xamarin.Android.Maps.Utils/files/1090797/MapUtilsCrash.zip)
